version: "3.7"

services:
  mongodb:
    image: mongo:4.2.3
    restart: always

    env_file:
      - ./docker-env/mongodb.env

    volumes:
      - mongodb:/data/db:rw

    ports:
      - ${EXTERNAL_PORT:-27017}:27017

networks:
  default:
    external:
      name: phantom-network

volumes:
  mongodb:
    external: false
