version: "3.7"

services:
  db2:
    image: ibmcom/db2:11.5.0.0
    restart: always
    privileged: true

    env_file:
      - ./docker-env/db2.env

    volumes:
      - db2:/database:rw

    ports:
      - ${EXTERNAL_PORT:-50000}:50000

networks:
  default:
    external:
      name: phantom-network

volumes:
  db2:
    external: false
