version: "3.7"

services:
  sonarqube:
    image: sonarqube
    restart: always

    volumes:
      - sonarqube:/opt/sonarqube/data:rw
      - sonarqube-config:/opt/sonarqube/conf:rw
      - sonarqube-logs:/opt/sonarqube/logs:rw

    ports:
      - ${EXTERNAL_PORT:-9000}:9000

networks:
  default:
    external:
      name: phantom-network

volumes:
  sonarqube:
    external: false
  sonarqube-config:
    external: false
  sonarqube-logs:
    external: false
