version: "3.7"

services:
  redis:
    image: redis:5.0.7
    restart: always
    env_file:
      - ./docker-env/redis.env

    volumes:
      - redis:/data:rw

    ports:
      - ${EXTERNAL_PORT:-6379}:6379

    command: redis-server --appendonly yes

networks:
  default:
    external:
      name: phantom-network

volumes:
  redis:
    external: false
