version: "3.3"

services:
    spring-boot:
        env_file: .env
        network_mode: "host"
        # restart: always

        image: "maven:3.6.2-jdk-8"

        volumes:
            - ./volumes/codigo:/var/volumes/codigo/
            - ./volumes/logs:/var/volumes/logs/
            - ./volumes/m2:/root/.m2

        ports:
            - "${PUERTO}:${PUERTO}"
            - "8787:8787"

        command: "mvn clean install spring-boot:run -f ${RUTA_CODIGO_DOCKER} \
        -Drun.arguments=\
        --server.port=${PUERTO},\
        --logging.file=${RUTA_LOGS_DOCKER}/${NOMBRE_ARCHIVO_LOGS} \
        --debug \
        -Drun.jvmArguments=\"-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8787\""
