version: "3.7"

services:
  postgres:
    image: postgres
    restart: always

    env_file:
      - ./docker-env/postgres.env

    volumes:
      - postgres:/volumes/sql/:rw

    ports:
      - ${EXTERNAL_PORT:-5432}:5432

networks:
  default:
    external:
      name: phantom-network

volumes:
  postgres:
    external: false
